# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-30 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20171129_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='login',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
    ]
